import { isHermesLaneRunId, isHermesOutcomeId, isOpaqueId, isReviewDispositionId, isVerificationRecordId } from "./ids";
import { HERMES_REVIEW_DISPOSITION_SCHEMA_VERSION, HERMES_VERIFICATION_RECORD_SCHEMA_VERSION, guardFailsClosed, hasExactKeys, isEvidenceRefs, isMetadataOnlyRecord, isRecord, isSafeText, isTimestampOrder, type HermesReviewerUnavailableExceptionV1, type ReviewDispositionV1, type ReviewHandoffV1, type VerificationRecordV1 } from "./types";

const VERIFICATION_FIELDS = ["verificationRecordId", "outcomeId", "laneRunId", "schemaVersion", "result", "target", "sourceFingerprint", "developerIdentity", "developerHome", "developerWorkspace", "evidenceRefs", "observedAt", "idempotencyKey", "createdAt", "metadataOnly", "rawPayloadRetained", "expectedOutcomeRevision", "expectedLaneRevision"] as const;
const DISPOSITION_FIELDS = ["reviewDispositionId", "verificationRecordId", "outcomeId", "developerLaneRunId", "schemaVersion", "disposition", "reviewerIdentity", "reviewerHome", "reviewerWorkspace", "reasonCode", "nextAction", "reviewedHeadSha", "evidenceRefs", "observedAt", "idempotencyKey", "createdAt", "metadataOnly", "rawPayloadRetained", "expectedOutcomeRevision", "expectedLaneRevision"] as const;
const EXCEPTION_FIELDS = ["exceptionId", "outcomeId", "laneRunId", "reason", "riskClass", "compensatingReviewRef", "recordedBy", "recordedAt", "reviewOrExpiryAt", "metadataOnly", "rawPayloadRetained"] as const;
const distinct = (...values: unknown[]) => new Set(values).size === values.length;
const capabilityBinding = (value: unknown) => isOpaqueId(value) && value.length <= 120;
const capabilityProof = (value: unknown) => isSafeText(value, 512) && value.length >= 24;
const timestampMillis = (value: unknown): number => typeof value === "string" ? Date.parse(value) : Number.NaN;
const pathParts = (value: string) => value.split(/[:\\/]+/).reduce<string[]>((parts, part) => { if (!part || part === ".") return parts; if (part === "..") { parts.pop(); return parts; } parts.push(part); return parts; }, []);
const overlaps = (left: string, right: string) => { const a = pathParts(left), b = pathParts(right); return a.every((part, index) => b[index] === part) || b.every((part, index) => a[index] === part); };

export function isVerificationRecordV1(value: unknown): value is VerificationRecordV1 {
  return guardFailsClosed(() => !!isRecord(value) && hasExactKeys(value, VERIFICATION_FIELDS) && isVerificationRecordId(value.verificationRecordId) && isHermesOutcomeId(value.outcomeId) && isHermesLaneRunId(value.laneRunId) && isMetadataOnlyRecord(value, HERMES_VERIFICATION_RECORD_SCHEMA_VERSION, ["observedAt", "createdAt"]) && isTimestampOrder(value, ["createdAt", "observedAt"]) && timestampMillis(value.observedAt) <= Date.now() && ["passed", "failed", "inconclusive"].includes(value.result as string) && isSafeText(value.target, 240) && isSafeText(value.sourceFingerprint, 240) && isSafeText(value.developerIdentity, 120) && isSafeText(value.developerHome, 240) && isSafeText(value.developerWorkspace, 240) && distinct(value.developerIdentity, value.developerHome, value.developerWorkspace) && isEvidenceRefs(value.evidenceRefs) && Number.isSafeInteger(value.expectedOutcomeRevision) && (value.expectedOutcomeRevision as number) > 0 && Number.isSafeInteger(value.expectedLaneRevision) && (value.expectedLaneRevision as number) > 0);
}
export function isReviewDispositionV1(value: unknown): value is ReviewDispositionV1 {
  return guardFailsClosed(() => !!isRecord(value) && hasExactKeys(value, DISPOSITION_FIELDS) && isReviewDispositionId(value.reviewDispositionId) && isVerificationRecordId(value.verificationRecordId) && isHermesOutcomeId(value.outcomeId) && isHermesLaneRunId(value.developerLaneRunId) && isMetadataOnlyRecord(value, HERMES_REVIEW_DISPOSITION_SCHEMA_VERSION, ["observedAt", "createdAt"]) && isTimestampOrder(value, ["createdAt", "observedAt"]) && timestampMillis(value.observedAt) <= Date.now() && ["approve", "rework", "technical_block"].includes(value.disposition as string) && ((value.disposition === "approve" && typeof value.reviewedHeadSha === "string" && /^[0-9a-f]{40}$/.test(value.reviewedHeadSha)) || (value.disposition !== "approve" && value.reviewedHeadSha === null)) && isSafeText(value.reviewerIdentity, 120) && isSafeText(value.reviewerHome, 240) && isSafeText(value.reviewerWorkspace, 240) && distinct(value.reviewerIdentity, value.reviewerHome, value.reviewerWorkspace) && isSafeText(value.reasonCode, 120) && isSafeText(value.nextAction, 360) && isEvidenceRefs(value.evidenceRefs) && Number.isSafeInteger(value.expectedOutcomeRevision) && (value.expectedOutcomeRevision as number) > 0 && Number.isSafeInteger(value.expectedLaneRevision) && (value.expectedLaneRevision as number) > 0);
}
export function isHermesReviewerUnavailableExceptionV1(value: unknown): value is HermesReviewerUnavailableExceptionV1 {
  return guardFailsClosed(() => !!isRecord(value) && hasExactKeys(value, EXCEPTION_FIELDS) && isOpaqueId(value.exceptionId) && isHermesOutcomeId(value.outcomeId) && isHermesLaneRunId(value.laneRunId) && isSafeText(value.reason, 120) && ["technical_block", "medium"].includes(value.riskClass as string) && isSafeText(value.compensatingReviewRef, 240) && isSafeText(value.recordedBy, 120) && value.metadataOnly === true && value.rawPayloadRetained === false && isTimestampOrder(value, ["recordedAt", "reviewOrExpiryAt"]) && timestampMillis(value.recordedAt) <= Date.now() && timestampMillis(value.reviewOrExpiryAt) > Date.now());
}
export function isReviewHandoffV1(value: unknown): value is ReviewHandoffV1 {
  return guardFailsClosed(() => {
    if (!isRecord(value) || !isVerificationRecordV1(value.verification)) return false;
    const verification = value.verification;
    if (hasExactKeys(value, ["verification", "developerCapabilityBindingId", "developerCapabilityProof"])) return capabilityBinding(value.developerCapabilityBindingId) && capabilityProof(value.developerCapabilityProof);
    if (verification.result !== "passed" || !isReviewDispositionV1(value.disposition) || !(hasExactKeys(value, ["verification", "disposition", "reviewerCapabilityBindingId", "reviewerCapabilityProof"]) || hasExactKeys(value, ["verification", "disposition", "unavailableReviewerException"]))) return false;
    const disposition = value.disposition;
    const exception = value.unavailableReviewerException;
    const exceptionValid = exception !== undefined && isHermesReviewerUnavailableExceptionV1(exception) && disposition.disposition === "technical_block" && exception.outcomeId === verification.outcomeId && exception.laneRunId === verification.laneRunId && Date.parse(exception.recordedAt) <= Date.parse(disposition.observedAt) && Date.parse(disposition.observedAt) < Date.parse(exception.reviewOrExpiryAt);
    return (exceptionValid || (exception === undefined && capabilityBinding(value.reviewerCapabilityBindingId) && capabilityProof(value.reviewerCapabilityProof))) && verification.verificationRecordId === disposition.verificationRecordId && verification.outcomeId === disposition.outcomeId && verification.laneRunId === disposition.developerLaneRunId && verification.expectedOutcomeRevision === disposition.expectedOutcomeRevision && verification.expectedLaneRevision === disposition.expectedLaneRevision && Date.parse(disposition.observedAt) >= Date.parse(verification.observedAt) && ![verification.developerIdentity, verification.developerHome, verification.developerWorkspace].some((developer) => [disposition.reviewerIdentity, disposition.reviewerHome, disposition.reviewerWorkspace].some((reviewer) => overlaps(developer, reviewer)));
  });
}
export const verificationRecordV1Fields = Object.freeze(VERIFICATION_FIELDS);
export const reviewDispositionV1Fields = Object.freeze(DISPOSITION_FIELDS);
