import { isHermesCitedSourceConfirmationReceiptId, isHermesCitedSourceRecordId, isHermesLaneRunId, isHermesOutcomeId, isOpaqueId } from "./ids";
import { HERMES_CITED_SOURCE_RECORD_SCHEMA_VERSION, guardFailsClosed, hasExactKeys, isEvidenceRefs, isRecord, isSafeText, isTimestampOrder, type HermesCitedSourceConfirmationReceiptV1, type HermesCitedSourceRecordV1 } from "./types";

const FIELDS = ["sourceRecordId", "outcomeId", "laneRunId", "schemaVersion", "sourceKind", "locator", "fingerprint", "citationRefs", "accessScope", "confidence", "observedAt", "reviewAt", "expiresAt", "supersedesSourceRecordId", "idempotencyKey", "expectedOutcomeRevision", "expectedLaneRevision", "metadataOnly", "rawPayloadRetained"] as const;
const RECEIPT_FIELDS = ["receiptId", "consumerType", "consumerId", "outcomeId", "laneRunId", "citedSourceRecordIds", "sourceSetFingerprintSha256", "expectedOutcomeRevision", "expectedLaneRevision", "confirmedAt", "metadataOnly", "rawPayloadRetained"] as const;

function isAllowlistedLocator(value: unknown): boolean {
  return typeof value === "string" && !value.includes("..") && /^(?:docs\/[a-z0-9][a-z0-9._/#-]*|delivery-evidence:[a-z0-9][a-z0-9:_-]*)$/i.test(value);
}

export function isHermesCitedSourceRecordV1(value: unknown): value is HermesCitedSourceRecordV1 {
  return guardFailsClosed(() => !!isRecord(value) && hasExactKeys(value, FIELDS) && isHermesCitedSourceRecordId(value.sourceRecordId) && typeof value.sourceRecordId === "string" && value.sourceRecordId.length <= 120 && isHermesOutcomeId(value.outcomeId) && isHermesLaneRunId(value.laneRunId) && value.schemaVersion === HERMES_CITED_SOURCE_RECORD_SCHEMA_VERSION && ["source_owned_document", "validated_delivery_evidence"].includes(value.sourceKind as string) && isAllowlistedLocator(value.locator) && ((value.sourceKind === "source_owned_document") === (typeof value.locator === "string" && value.locator.startsWith("docs/"))) && isSafeText(value.fingerprint, 240) && isEvidenceRefs(value.citationRefs) && ["implementation_verification", "independent_review", "verification_and_review"].includes(value.accessScope as string) && ["high", "medium"].includes(value.confidence as string) && isTimestampOrder(value, ["observedAt", "reviewAt", "expiresAt"]) && Date.parse(value.reviewAt as string) < Date.parse(value.expiresAt as string) && Date.parse(value.observedAt as string) <= Date.now() && (value.supersedesSourceRecordId === null || (isHermesCitedSourceRecordId(value.supersedesSourceRecordId) && typeof value.supersedesSourceRecordId === "string" && value.supersedesSourceRecordId.length <= 120)) && isOpaqueId(value.idempotencyKey) && typeof value.idempotencyKey === "string" && value.idempotencyKey.length <= 180 && Number.isSafeInteger(value.expectedOutcomeRevision) && (value.expectedOutcomeRevision as number) > 0 && Number.isSafeInteger(value.expectedLaneRevision) && (value.expectedLaneRevision as number) > 0 && value.metadataOnly === true && value.rawPayloadRetained === false);
}

export function isHermesCitedSourceConfirmationReceiptV1(value: unknown): value is HermesCitedSourceConfirmationReceiptV1 {
  return guardFailsClosed(() => !!isRecord(value) && hasExactKeys(value, RECEIPT_FIELDS) && isHermesCitedSourceConfirmationReceiptId(value.receiptId) && typeof value.receiptId === "string" && value.receiptId.length <= 120 && ["verification", "review"].includes(value.consumerType as string) && isOpaqueId(value.consumerId) && typeof value.consumerId === "string" && value.consumerId.length <= 120 && isHermesOutcomeId(value.outcomeId) && isHermesLaneRunId(value.laneRunId) && Array.isArray(value.citedSourceRecordIds) && value.citedSourceRecordIds.length > 0 && value.citedSourceRecordIds.length <= 64 && value.citedSourceRecordIds.every(isHermesCitedSourceRecordId) && new Set(value.citedSourceRecordIds).size === value.citedSourceRecordIds.length && value.citedSourceRecordIds.every((id, index, ids) => index === 0 || ids[index - 1] < id) && typeof value.sourceSetFingerprintSha256 === "string" && /^sha256:[a-f0-9]{64}$/.test(value.sourceSetFingerprintSha256) && Number.isSafeInteger(value.expectedOutcomeRevision) && (value.expectedOutcomeRevision as number) > 0 && Number.isSafeInteger(value.expectedLaneRevision) && (value.expectedLaneRevision as number) > 0 && isTimestampOrder(value, ["confirmedAt"]) && value.metadataOnly === true && value.rawPayloadRetained === false);
}

export const hermesCitedSourceRecordV1Fields = Object.freeze(FIELDS);
export const hermesCitedSourceConfirmationReceiptV1Fields = Object.freeze(RECEIPT_FIELDS);
